const invoice = [
  {
    id: '1',
    ts: 'TS252612531',
    invoiceNumber: '6290397298',
    date: '2025-10-16T16:54:00Z',
    dateDisplay: '16-10-2025 16:54',
    status: 'Paid',
    paid: true,
    currency: 'INR',
    amount: 250,
    amountDisplay: '₹ 250.00',
  },
  {
    id: '2',
    ts: 'TS252612532',
    invoiceNumber: '6290397299',
    date: '2025-10-15T11:20:00Z',
    dateDisplay: '15-10-2025 11:20',
    status: 'Unpaid',
    paid: false,
    currency: 'INR',
    amount: 1200,
    amountDisplay: '₹ 1,200.00',
  },
  {
    id: '3',
    ts: 'TS252612533',
    invoiceNumber: '6290397300',
    date: '2025-09-30T09:05:00Z',
    dateDisplay: '30-09-2025 09:05',
    status: 'Paid',
    paid: true,
    currency: 'INR',
    amount: 75.5,
    amountDisplay: '₹ 75.50',
  },
  {
    id: '4',
    ts: 'TS252612534',
    invoiceNumber: '6290397301',
    date: '2025-10-01T14:40:00Z',
    dateDisplay: '01-10-2025 14:40',
    status: 'Refunded',
    paid: false,
    currency: 'INR',
    amount: 300,
    amountDisplay: '₹ 300.00',
  },
  {
    id: '5',
    ts: 'TS252612535',
    invoiceNumber: '6290397302',
    date: '2025-08-21T18:30:00Z',
    dateDisplay: '21-08-2025 18:30',
    status: 'Paid',
    paid: true,
    currency: 'INR',
    amount: 999.99,
    amountDisplay: '₹ 999.99',
  },
  {
    id: '6',
    ts: 'TS252612536',
    invoiceNumber: '6290397303',
    date: '2025-07-10T08:15:00Z',
    dateDisplay: '10-07-2025 08:15',
    status: 'Overdue',
    paid: false,
    currency: 'INR',
    amount: 450,
    amountDisplay: '₹ 450.00',
  },
  {
    id: '7',
    ts: 'TS252612537',
    invoiceNumber: '6290397304',
    date: '2025-06-02T12:00:00Z',
    dateDisplay: '02-06-2025 12:00',
    status: 'Paid',
    paid: true,
    currency: 'INR',
    amount: 1500,
    amountDisplay: '₹ 1,500.00',
  },
];

const products = [
  {
    id: '1',
    title: 'Chicken Biryani',
    price: 2500,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '2', title: 'Paneer Tikka', price: 1800},
  {
    id: '3',
    title: 'Butter Chicken',
    price: 3200,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {
    id: '4',
    title: 'Veg Fried Rice',
    price: 1500,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {
    id: '5',
    title: 'Mutton Curry',
    price: 3500,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '6', title: 'Masala Dosa', price: 1200},
  {
    id: '7',
    title: 'Chicken Shawarma',
    price: 2000,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '8', title: 'Prawn Curry', price: 3600},
  {
    id: '9',
    title: 'Veg Pulao',
    price: 1400,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '10', title: 'Fish Fry', price: 2800},
  {
    id: '11',
    title: 'Chicken 65',
    price: 2300,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {
    id: '12',
    title: 'Egg Curry',
    price: 1700,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {
    id: '13',
    title: 'Chole Bhature',
    price: 1600,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '14', title: 'Paneer Butter Masala', price: 2000},
  {
    id: '15',
    title: 'Grilled Sandwich',
    price: 900,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '16', title: 'Momos', price: 800},
  {
    id: '17',
    title: 'Chicken Lollipop',
    price: 2200,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '18', title: 'Veg Noodles', price: 1300},
  {
    id: '19',
    title: 'Tandoori Roti',
    price: 300,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '20', title: 'Chocolate Brownie', price: 1100},
  {
    id: '21',
    title: 'Pav Bhaji',
    price: 1300,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '22', title: 'Idli Sambar', price: 800},
  {
    id: '23',
    title: 'Veg Burger',
    price: 1500,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '24', title: 'Chicken Sandwich', price: 1600},
  {
    id: '25',
    title: 'Dal Makhani',
    price: 1700,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '26', title: 'Aloo Paratha', price: 900},
  {
    id: '27',
    title: 'Chicken Tikka',
    price: 2400,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '28', title: 'Paneer Pakora', price: 1100},
  {
    id: '29',
    title: 'Samosa',
    price: 600,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '30', title: 'Spring Roll', price: 800},
  {
    id: '31',
    title: 'Fried Chicken',
    price: 2500,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '32', title: 'Veg Cutlet', price: 1000},
  {
    id: '33',
    title: 'Chicken Soup',
    price: 1200,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '34', title: 'Tomato Soup', price: 900},
  {
    id: '35',
    title: 'Caesar Salad',
    price: 1400,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '36', title: 'Greek Salad', price: 1300},
  {
    id: '37',
    title: 'Veg Pizza',
    price: 2000,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '38', title: 'Chicken Pizza', price: 2400},
  {
    id: '39',
    title: 'Garlic Bread',
    price: 900,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '40', title: 'Pasta Alfredo', price: 1900},
  {
    id: '41',
    title: 'Pasta Arrabiata',
    price: 1800,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '42', title: 'Veg Manchurian', price: 1500},
  {
    id: '43',
    title: 'Gobi 65',
    price: 1300,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '44', title: 'Paneer Chilli', price: 1600},
  {
    id: '45',
    title: 'Chicken Fried Rice',
    price: 1800,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '46', title: 'Veg Momos', price: 900},
  {
    id: '47',
    title: 'Corn Soup',
    price: 1000,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '48', title: 'Sweet Corn Salad', price: 1100},
  {
    id: '49',
    title: 'Egg Fried Rice',
    price: 1600,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '50', title: 'Fruit Salad', price: 1200},
  {
    id: '51',
    title: 'Chicken Roll',
    price: 1400,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '52', title: 'Veg Roll', price: 1100},
  {
    id: '53',
    title: 'Paneer Roll',
    price: 1500,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '54', title: 'French Fries', price: 900},
  {
    id: '55',
    title: 'Masala Fries',
    price: 1000,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '56', title: 'Onion Rings', price: 1100},
  {
    id: '57',
    title: 'Chicken Popcorn',
    price: 1600,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '58', title: 'Veg Puffs', price: 700},
  {
    id: '59',
    title: 'Egg Puff',
    price: 900,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '60', title: 'Paneer Puff', price: 1000},
  {
    id: '61',
    title: 'Chocolate Cake',
    price: 1800,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '62', title: 'Vanilla Cake', price: 1700},
  {
    id: '63',
    title: 'Cheesecake',
    price: 2200,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '64', title: 'Ice Cream Sundae', price: 1300},
  {
    id: '65',
    title: 'Brownie Fudge',
    price: 1600,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '66', title: 'Donut', price: 1000},
  {
    id: '67',
    title: 'Cupcake',
    price: 900,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '68', title: 'Waffles', price: 1500},
  {
    id: '69',
    title: 'Pancakes',
    price: 1300,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '70', title: 'Fruit Tart', price: 1400},
  {
    id: '71',
    title: 'Veg Thali',
    price: 2500,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '72', title: 'Chicken Thali', price: 2800},
  {
    id: '73',
    title: 'Fish Curry',
    price: 3100,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '74', title: 'Prawn Fry', price: 3200},
  {
    id: '75',
    title: 'Egg Biryani',
    price: 2300,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '76', title: 'Veg Biryani', price: 2100},
  {
    id: '77',
    title: 'Mutton Biryani',
    price: 3700,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '78', title: 'Paneer Biryani', price: 2400},
  {
    id: '79',
    title: 'Dal Fry',
    price: 1300,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '80', title: 'Rajma Chawal', price: 1600},
  {
    id: '81',
    title: 'Kadai Paneer',
    price: 1900,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '82', title: 'Palak Paneer', price: 2000},
  {
    id: '83',
    title: 'Malai Kofta',
    price: 2200,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '84', title: 'Mix Veg Curry', price: 1700},
  {
    id: '85',
    title: 'Aloo Gobi',
    price: 1500,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '86', title: 'Bhindi Masala', price: 1400},
  {
    id: '87',
    title: 'Jeera Rice',
    price: 1200,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '88', title: 'Plain Rice', price: 1000},
  {
    id: '89',
    title: 'Butter Naan',
    price: 400,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '90', title: 'Garlic Naan', price: 500},
  {
    id: '91',
    title: 'Roti',
    price: 300,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '92', title: 'Paratha', price: 600},
  {
    id: '93',
    title: 'Curd Rice',
    price: 900,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '94', title: 'Lemon Rice', price: 1000},
  {
    id: '95',
    title: 'Veg Curry',
    price: 1500,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '96', title: 'Chicken Curry', price: 2500},
  {
    id: '97',
    title: 'Egg Curry Masala',
    price: 1800,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '98', title: 'Tandoori Chicken', price: 3000},
  {
    id: '99',
    title: 'Grilled Fish',
    price: 3200,
    image: require('./../../asset/images/productimage.jpg'),
  },
  {id: '100', title: 'Gulab Jamun', price: 900},
];

const aboutScreenNavigations = [
  {
    name: 'About Billtrack App',
    url: 'https://billtrack.co.in/about',
  },
  {
    name: 'Privacy Policy',
    url: 'https://billtrack.co.in/privacy-policy',
  },
  {
    name: 'Terms and Conditions',
    url: 'https://billtrack.co.in/terms-condition',
  },
  {
    name: 'Refund Policy',
    url: 'https://billtrack.co.in/refund-policy',
  },
];

const helpAndSupportNavigations = [
  {
    name: 'General Inquiry',
    url: 'https://billtrack.co.in/contact',
  },
  {
    name: 'Feedback & Suggestions',
    url: 'https://billtrack.co.in/contact',
  },
  {
    name: 'Subscription Related Query',
    url: 'https://billtrack.co.in/contact',
  },
  {
    name: 'SMS Related Query',
    url: 'https://billtrack.co.in/contact',
  },
];

export {invoice, products, aboutScreenNavigations, helpAndSupportNavigations};
